services:
  db:
    image: mysql:latest
    container_name: project_travel_agency
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_travel_agency
      MYSQL_USER: project_travel_agency
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./initialization.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
  dbdata:
